spring.application.name=backend

# MySQL connection (DB name ASD)
spring.datasource.url=jdbc:mysql://localhost:3306/ASD
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Force dialect (prevents dialect-detection failure)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


server.port=8081

# mail details
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=6be7287feaa23f
spring.mail.password=960ac69c05b80d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# frontend url
app.frontend.base-url=http://localhost:5173

#jwt secret
jwt.secret=mysecretkeymysecretkeymysecretkey12

fastapi.url=http://localhost:8000/predict
fastapi.api-key=SusamSecretAndhoMancheleMovieHeryo

# ===============================
# KHALTI SANDBOX CONFIG
# ===============================
khalti.base-url=https://dev.khalti.com/api/v2
khalti.public-key=ee2a224b31e54aa6a7125d4820e20f9a
khalti.secret-key=a97223ef88114332802b9be240831586
khalti.website-url=http://localhost:5173
khalti.return-url=http://localhost:5173/payment-success


#elevenlabs

elevenlabs.api-key=f2046879fe367e256bddb9d5b63091c8c1d61b362e1a9857c8eaade043acf72a
elevenlabs.voice-id=EXAVITQu4vr4xnSDxMaL
elevenlabs.model-id=eleven_multilingual_v2
